### ISSUE TITLE
Failed to resolve remote address

### ISSUE THREAD

**Issue by whollacsek** [dokku/service-proxy#72]
## Description of problem

Error when deploying the service-proxy with part of the service name uppercased.

### How reproducible

Run the script below:

### Steps to Reproduce

```bash
SERVICE_NAME="typesense-abc"
SERVICE_PROXY_APP="service-proxy-$SERVICE_NAME"
PUBLIC_URL="typesense.abc.com"

# Create the Typesense instance
dokku typesense:create $SERVICE_NAME

# See: https://github.com/dokku/service-proxy
dokku apps:create $SERVICE_PROXY_APP
dokku config:set $SERVICE_PROXY_APP SERVICE_NAME=$SERVICE_NAME SERVICE_TYPE=typesense
dokku domains:set "$SERVICE_PROXY_APP" "$PUBLIC_URL"

# Link the Typesense instance to service-proxy
dokku typesense:link $SERVICE_NAME $SERVICE_PROXY_APP

# Deploy service-proxy
dokku git:from-image $SERVICE_PROXY_APP dokku/service-proxy:latest
```

#### Actual Results

```
=====> Start of service-proxy-typesense-abc container output (66efb2a86279 web.1)
       go-tcp-proxy (0.0.0-src) proxing from 0.0.0.0:5000 to dokku-TYPESENSE-TYPESENSE_ABC:8108
       Failed to resolve remote address: lookup dokku-TYPESENSE-TYPESENSE_ABC on 185.12.64.1:53: no such host
```

#### Expected Results

No error and app successfully deployed.

### `dokku report APP_NAME` output

> This is required! Issues missing this information may be closed.
>
> For problems affecting all applications, the report output for a broken application is useful for our debugging.
> In these cases, you may run `dokku report` without any arguments to display the top-level reporting information.

### Additional information

- App container inspect output (if applicable) via `dokku ps:inspect APP_NAME`
- The nginx configuration (if applicable) via `dokku nginx:show-config APP_NAME`
- Link to the exact repository being deployed (if possible/applicable):
- Output of failing Dokku commands after running `dokku trace:on`
  (BEWARE: `trace:on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXX):

**Comment by josegonzalez** [comment]
Okay this should be fixed with the latest release of the service-proxy image. Thanks for reporting the problem.

**Comment by whollacsek** [comment]
Thanks @josegonzalez !
